# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.


   config.vm.define "maquina_ansible" do |maquina_ansible|
      maquina_ansible.vm.box = "aws"
        maquina_ansible.vm.provider :aws do |aws, override|
        aws.access_key_id = "AKIAIPC4DY3U44GAPV7Q"
        aws.secret_access_key = "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"
        aws.keypair_name = "hito3"

        
        aws.tags = {
		    'Name' => 'Vagrant con ansible',
		    'Environment' => 'vagrant-sandbox'
        } 
        
        aws.region = "us-east-1"
        aws.ami = "ami-1081b807"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]
        
        override.ssh.username = "ubuntu"  #ec2-user
        override.ssh.private_key_path = "~/hito3.pem"
      end
        
      maquina_ansible.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yml"
      end
   end

   config.vm.define "maquina_chef" do |maquina_chef|
      maquina_chef.vm.box = "aws"
        maquina_chef.vm.provider :aws do |aws, override|
        aws.access_key_id = "AKIAIPC4DY3U44GAPV7Q"
        aws.secret_access_key = "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"
        aws.keypair_name = "hito3"

        
        aws.tags = {
		    'Name' => 'Vagrant con chef',
		    'Environment' => 'vagrant-sandbox'
        } 
        
        aws.region = "us-east-1"
        aws.ami = "ami-1081b807"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]
        
        override.ssh.username = "ubuntu"  #ec2-user
        override.ssh.private_key_path = "~/hito3.pem"
      end
        
      maquina_chef.vm.provision "chef_solo" do |chef|
        chef.add_recipe "mystudentbot"
      end
   end


end
