Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.


   config.vm.define "maquina_ansible" do |maquina_ansible|
      maquina_ansible.vm.box = "aws"
        maquina_ansible.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Vagrant con ansible',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "us-east-1"
        aws.ami = "ami-1081b807"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]

        override.ssh.username = "ubuntu"  #ec2-user
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      maquina_ansible.vm.provision :ansible do |ansible|
        ansible.playbook = "playbook.yml"
      end
   end

   config.vm.define "maquina_chef" do |maquina_chef|
      maquina_chef.vm.box = "aws"
        maquina_chef.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Vagrant con chef',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "us-east-1"
        aws.ami = "ami-1081b807"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]

        override.ssh.username = "ubuntu"  #ec2-user
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      maquina_chef.vm.provision "chef_solo" do |chef|
        chef.add_recipe "mystudentbot"
      end
   end


end
