Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://atlas.hashicorp.com/search.


   config.vm.define "maquina_bot" do |maquina_bot|
      maquina_bot.vm.box = "aws"
        maquina_bot.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Mystudentbot bot',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "us-east-1"
        aws.ami = "ami-1081b807"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]

        override.ssh.username = "ubuntu"  #ec2-user
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      maquina_bot.vm.provision :ansible do |ansible|
        ansible.playbook = "Playbooks/playbook-bot.yml"
      end
   end

   config.vm.define "maquina_academico_gestion" do |maquina_academico_gestion|
      maquina_academico_gestion.vm.box = "aws"
        maquina_academico_gestion.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Mystudentbot academico/gestion',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "us-east-1"
        aws.ami = "ami-1081b807"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]

        override.ssh.username = "ubuntu"  #ec2-user
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      maquina_academico_gestion.vm.provision :ansible do |ansible|
        ansible.playbook = "Playbooks/playbook-academico-gestion.yml"
      end
   end
   
   config.vm.define "maquina_gastos" do |maquina_gastos|
      maquina_gastos.vm.box = "aws"
        maquina_gastos.vm.provider :aws do |aws, override|
        aws.access_key_id = ENV['AWS_KEY']
        aws.secret_access_key = ENV['AWS_SECRET']
        aws.keypair_name = ENV['AWS_KEYNAME']


        aws.tags = {
            'Name' => 'Mystudentbot gastos',
            'Environment' => 'vagrant-sandbox'
        } 

        aws.region = "us-east-1"
        aws.ami = "ami-1081b807"
        aws.instance_type = "t2.micro"
        aws.security_groups = ["vagrant"]

        override.ssh.username = "ubuntu"  #ec2-user
        override.ssh.private_key_path = ENV['AWS_KEYPATH']
      end

      maquina_gastos.vm.provision :ansible do |ansible|
        ansible.playbook = "Playbooks/playbook-gastos.yml"
      end
   end

end
